
all: proj1-design proj2-design proj3-design proj4-design

proj1-design: proj1-design.tex
	pdflatex proj1-design.tex

proj2-design: proj2-design.tex
	pdflatex proj2-design.tex

proj3-design: proj3-design.tex
	pdflatex proj3-design.tex

proj4-design: proj4-design.tex
	pdflatex proj4-design.tex

clean:
	rm *.pdf *.log *.aux
